ETF_CONFIG = {
    "SOXX": [
        {"id": "AVGO", "label": "Broadcom"},
        {"id": "NVDA", "label": "Nvidia"},
        {"id": "QCOM", "label": "Qualcomm"},
        {"id": "TXN", "label": "TexasInst"},
        {"id": "AMD", "label": "AMD"},
        {"id": "KLAC", "label": "KLA"},
        {"id": "ADI", "label": "Analog"},
        {"id": "LRCX", "label": "LamRes"},
        {"id": "MRVL", "label": "Marvell"},
        {"id": "INTC", "label": "Intel"}
    ],
    "Indices": [
       # {"id": "^DJI", "label": "Dow Jones"},
        {"id": "^GSPC", "label": "S&P 500"},
        {"id": "^IXIC", "label": "NASDAQ Composite"},
        #{"id": "^RUT", "label": "Russell 2000"},
        #{"id": "^VIX", "label": "Volatility Index (VIX)"},
        {"id": "^N225", "label": "Nikkei 225 - Japan"},
        {"id": "^HSI", "label": "Hang Seng - Hong Kong"},
        {"id": "^FTSE", "label": "FTSE 100 - UK"},
        {"id": "^GDAXI", "label": "DAX - Germany"},
        #{"id": "^FCHI", "label": "CAC 40 - France"},
        {"id": "^AXJO", "label": "ASX 200 - Australia"},
        #{"id": "^BSESN", "label": "Sensex - India"}
    ],
    "Currencies": [
        {"id": "USDJPY=X", "label": "USD/JPY"},
        {"id": "AUDUSD=X", "label": "AUD/USD"},
        {"id": "AUDNZD=X", "label": "AUD/NZD"},
        {"id": "USDCHF=X", "label": "USD/CHF"},
        {"id": "EURUSD=X", "label": "EUR/USD"},
        {"id": "EURJPY=X", "label": "EUR/JPY"}
    ],
    "Crypto": [
        {"id": "BTC-USD", "label": "Bitcoin"},
        {"id": "ETH-USD", "label": "Ethereum"},
        {"id": "SOL-USD", "label": "Solana"},
        {"id": "DOGE-USD", "label": "Dogecoin"}
    ],
    "ASX20": [
        {"id": "ALL.AX", "label": "Aristocrat"},
        {"id": "ANZ.AX", "label": "ANZ"},
        {"id": "BHP.AX", "label": "BHP"},
        {"id": "CBA.AX", "label": "Commonwealth"},
        {"id": "CSL.AX", "label": "CSL"},
        {"id": "FMG.AX", "label": "Fortescue"},
        {"id": "GMG.AX", "label": "Goodman"},
        {"id": "MQG.AX", "label": "Macquarie"},
        {"id": "NAB.AX", "label": "NAB"},
        {"id": "REA.AX", "label": "REA"},
        {"id": "RIO.AX", "label": "RioTinto"},
        {"id": "TCL.AX", "label": "Transurban"},
        {"id": "TLS.AX", "label": "Telstra"},
        {"id": "WBC.AX", "label": "Westpac"},
        {"id": "WES.AX", "label": "Wesfarmers"},
        {"id": "WOW.AX", "label": "Woolworths"},
        {"id": "XRO.AX", "label": "Xero"}
    ],
    "NASDAQ20": [
        {"id": "AAPL", "label": "Apple"},
        {"id": "MSFT", "label": "Microsoft"},
        {"id": "NVDA", "label": "Nvidia"},
        {"id": "AMZN", "label": "Amazon"},
        {"id": "META", "label": "Meta"},
        {"id": "TSLA", "label": "Tesla"},
        {"id": "COST", "label": "Costco"},
        {"id": "GOOGL", "label": "AlphabetA"},
        {"id": "GOOG", "label": "AlphabetC"},
        {"id": "NFLX", "label": "Netflix"},
        {"id": "ADBE", "label": "Adobe"},
        {"id": "AVGO", "label": "Broadcom"},
        {"id": "AMGN", "label": "Amgen"},
        {"id": "INTC", "label": "Intel"},
        {"id": "CSCO", "label": "Cisco"},
        {"id": "TXN", "label": "TexasInst"},
        {"id": "QCOM", "label": "Qualcomm"},
        {"id": "MU", "label": "Micron"},
        {"id": "PEP", "label": "Pepsi"},
        {"id": "ADP", "label": "ADP"}
    ],
    "NIKKEI10": [
        {"id": "9983.T", "label": "FastRetail"},
        {"id": "8035.T", "label": "TokyoElec"},
        {"id": "6857.T", "label": "Advantest"},
        {"id": "9984.T", "label": "SoftBank"},
        {"id": "4063.T", "label": "ShinEtsu"},
        {"id": "9433.T", "label": "KDDI"},
        {"id": "6762.T", "label": "TDK"},
        {"id": "6098.T", "label": "Recruit"},
        {"id": "4543.T", "label": "Terumo"},
        {"id": "6954.T", "label": "Fanuc"}
    ],
    "HANGSENG": [
        {"id": "9618.HK", "label": "JD"},
        {"id": "3690.HK", "label": "Meituan"},
        {"id": "9988.HK", "label": "Alibaba"},
        {"id": "1024.HK", "label": "Kuaishou"},
        {"id": "1810.HK", "label": "Xiaomi"},
        {"id": "2015.HK", "label": "LiAuto"},
        {"id": "9999.HK", "label": "NetEase"},
        {"id": "9868.HK", "label": "XPeng"},
        {"id": "9961.HK", "label": "Trip.com"},
        {"id": "6690.HK", "label": "Haier"},
        {"id": "9888.HK", "label": "Baidu"},
        {"id": "9626.HK", "label": "Bilibili"},
        {"id": "2382.HK", "label": "SunnyOpt"},
        {"id": "6618.HK", "label": "JDHealth"}
    ]
}
