stock_options = {
    "Australian Stock Exchange": "^AXJO",
    "NASDAQ 100": "^NDX",
    "Bitcoin": "BTC-USD",
    "Nikkei 225 - Japan": "^N225",
    "Hang Seng - Hong Kong": "^HSI",
    "FTSE 100 - UK": "^FTSE",
    "DAX - Germany": "^GDAXI",
    "CAC 40 - France": "^FCHI",
    "S&P 500 - US": "^GSPC",
    "Toronto Stock Exchange": "^GSPTSE",
    "NIFTY 50 - India": "^NSEI",
    "IBEX 35 - Spain": "^IBEX",
    "AEX - Netherlands": "^AEX",
    "FTSE MIB - Italy": "^FTSEMIB",
    "Bovespa - Brazil": "^BVSP",
    "IPC - Mexico": "^MEXBOL",
    "Volatility Index (VIX)": "^VIX",
    "USD/CHF": "USDCHF=X",
    "USD/JPY": "USDJPY=X",
    "AUD/USD": "AUDUSD=X",
    "EUR/USD": "EURUSD=X",
    "iShares Semiconductor ETF": "SOXX"
}
